name: 构建和发布签到系统Agent

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: 构建
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: checkin-agent
            asset_name: checkin-agent-linux-amd64
          - os: windows-latest
            artifact_name: checkin-agent.exe
            asset_name: checkin-agent-windows-amd64.exe
          - os: macos-latest
            artifact_name: checkin-agent
            asset_name: checkin-agent-darwin-amd64

    steps:
    - uses: actions/checkout@v4

    - name: 设置Go环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        check-latest: true

    - name: 获取依赖
      run: go mod tidy

    - name: 构建
      run: go build -v -o ${{ matrix.artifact_name }}

    - name: 上传构建结果
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
        retention-days: 5

  release:
    name: 发布版本
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: 下载构建结果
        uses: actions/download-artifact@v4

      - name: 显示结构
        run: ls -R

      - name: 创建发布
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: 发布 ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            checkin-agent-linux-amd64/checkin-agent
            checkin-agent-windows-amd64.exe/checkin-agent.exe
            checkin-agent-darwin-amd64/checkin-agent
